# -*- coding: utf-8 -*-
"""COTW-8: Math Quiz Master.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qRYCyB27RkgeDh3Rh1Syq9iCa_xuvusK

##Math Quiz Master
In this challenge, you will need to answer 21 arithmetic questions with speed and accuracy. However, there's a catch - you'll need to progress through three levels, each with a higher difficulty and shorter time limit! You'll face 7 questions in each level, with the first level allowing 30 seconds, the second level 20 seconds, and the final level only 10 seconds to complete. Do you accept the challenge? Follow the steps below and see how far you can go in achieving the title of a true Math Quiz Master!


    Step 1: Import the random module.
    Step 2: Define the function quiz() that will hold the entire quiz program.
    Step 3: Initialize the score, num_questions, and high_score variables to 0, 10, and the value of the load_high_score() function respectively.
    Step 4: Display a welcome message to the user and prompt them to start the quiz.
    Step 5: Begin a loop that will run for num_questions iterations.
    Step 6: Within the loop, generate two random numbers and an arithmetic operator using the random module.
    Step 7: Calculate the correct answer based on the generated numbers and operator.
    Step 8: Prompt the user with the generated arithmetic question and retrieve their answer.
    Step 9: Check if the answer is correct, increment the score if it is, and display a message to the user indicating whether their answer was correct or incorrect.
    Step 10: After all questions have been answered, display the user's score and check if it is higher than the high score.If it is, save the new high score using the save_high_score() function. Otherwise, display the high score to the user and prompt them to try again.

If the user answers 7 or more questions correctly within 30 seconds, they move on to the next level with 7 questions to answer in 20 seconds. If they pass this level, they move on to the last level with 7 questions to answer in 10 seconds.
"""

###################################################

#Write your code here

###################################################

"""###**Good luck and have fun!** """